spring.application.name: RealEstate
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/real_estate
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8181
