spring.application.name: RealEstate
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/real_estate
    username: root
    password: teamone
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: Sajal
      password: Hello@123
      roles: ADMIN, USER
server:
  port: 8181

